server:
  port: 9001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl.defaultZone: http://localhost:${server.port}/eureka/
