#指定服务端口
server:
  port: 2002
#指定微服务名称
spring:
  application:
    name: zero-cloud-member
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
        enabled: false
#指定服务中心位置
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/
    registry-fetch-interval-seconds: 5
management:
  security:
    enabled: false
logging:
  file: "target/zero-cloud-sample.log"