#指定服务端口
server:
  port: 2003
#feign:
#  hystrix:
#    enabled: true
#指定微服务名称
spring:
#  sleuth:
#    sampler:
#      percentage: 1
#  boot:
#    admin:
#      routes:
#        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
#      turbine:
#        clusters: default
#        location: turbine
#        enabled: false
  datasource:
      druid:
        db-type: mysql
        driver-class-name: com.mysql.jdbc.Driver
        url: ${mysql.url}
        username: ${mysql.user}
        password: ${mysql.password}
        initialSize: 10
        max-active: 20
        minIdle: 5
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        filter:
          config:
            enabled: true

#  zipkin:
#    service:
#      name: zero-cloud-member
#    base-url: http://localhost:9411
  flyway: #flyway 数据库版本管理工具
    url: ${mysql.url}
    user: ${mysql.user}
    password: ${mysql.password}
    enabled: true
#指定服务中心位置
eureka:
  instance:
    hostname: test
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://10.112.65.89:9001/eureka/
    registry-fetch-interval-seconds: 5
#management:
#  endpoint:
#    jolokia:
#      enabled: true
debug: false
mysql:
  url: jdbc:mysql://localhost:3306/cloud_member?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  user: xhyan
  password: 1234
