# 服务暴露端口
server:
  port: 8002
spring:
  application:
#   应用名称
    name: zero-admin-turbine
  boot:
    admin:
#     boot admin 管理地址
      url: http://localhost:8002
      username: "${security.user.name}"
      password: "${security.user.password}"
      client:
        metadata:
          user.name: "${security.user.name}"
          user.password: "${security.user.password}"
      discovery:
        ignored-services: zero-admin-turbine
#        prefer-ip: true
management:
  security:
    enabled: false
  context-path: "/actuator"
security:
  user:
    name: xhyan
    password: 1234
# eureka注册中心中心配置
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/
    registry-fetch-interval-seconds: 5
logging:
  file: "zero-admin-turbine/target/zero-admin-turbine.log"
