# 服务暴露端口
server:
  port: 8002
spring:
  application:
#   应用名称
    name: zero-admin-turbine
# eureka注册中心中心配置
eureka:
  instance:
    hostname: localhost
    #最小过期时间
    lease-expiration-duration-in-seconds: 10
    #最小更新时间
    lease-renewal-interval-in-seconds: 10
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://10.112.65.89:9001}/eureka/
logging:
  file: "zero-admin-turbine/target/zero-admin-turbine.log"
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
debug: true