server:
  port: 7001

spring:
  application:
    name: zero-cloud-config
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/xhyan/spring-cloud-learn/
          search-paths: config-server/zero-cloud-account

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/