server:
  port: 1001

spring:
  application:
    name: zero-hystrix-turbine

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/

turbine:
  app-config: zero-cloud-account,zero-cloud-member
  cluster-name-expression: "'default'"
  combine-host-port: false
  aggregator:
    clusterConfig: default
