server:
  port: 5555

spring:
  application:
    name: zero-cloud-gateway

zuul:
  routes:
    account:
      path: api/account/**
      serviceId: zero-cloud-account
    member:
      path: api/member/**
      serviceId: zero-cloud-member

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/