#指定服务端口
server:
  port: 2001
#指定微服务名称
spring:
  application:
    name: account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_account?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: xhyan
    password: 1234
    initialSize: 10
    minIdle: 5
    maeBetweenEvictionRunsMillis: 60000
    minxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
#mybatis配置
mybatis:
  type-aliases-package: com.xhyan.zero.cloud.account.model
  mapper-locations: classpath:mapper/*.xml
#通用mapper配置
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
#pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#指定服务中心位置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/
#flyway 数据库版本管理工具
flyway:
  url: jdbc:mysql://127.0.0.1:3306/cloud_account?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
  user: xhyan
  password: 1234
  enabled: true
debug: true
zero:
  converter:
    scan-packages: com.xhyan.zero.cloud.account.dto,com.xhyan.zero.cloud.account.model
    enable: true
