server:
  port: 7002
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        serviceId: config-client
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
