server:
  port: 7002

spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/
