#指定服务端口
server:
  port: 2001
#指定微服务名称
spring:
  application:
    name: zero-cloud-account
  devtools:
    #热加载
    livereload:
      enabled: false
    #是否开启自动重启
    restart:
      enabled: false
  zipkin:
    service:
      name: zero-cloud-account
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true
#指定服务中心位置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:9001/eureka/
debug: true